In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("titanic.csv")
df.head()

,survived,pclass,name,sex,age,fare,sibsp,parch
0,0,3,"Braund, Mr. Owen Harris",male,22.0,7.2500,1,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1,0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,0,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1,0
4,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  714 non-null    int64
 1   pclass    714 non-null    int64
 2   name      714 non-null    object
 3   sex       714 non-null    object
 4   age       714 non-null    float64
 5   fare      714 non-null    float64
 6   sibsp     714 non-null    int64
 7   parch     714 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 44.8+ KB

In [5]:
df.isnull().sum()

survived    0
pclass      0
name        0
sex         0
age         0
fare        0
sibsp       0
parch       0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  714 non-null    int64
 1   pclass    714 non-null    int64
 2   name      714 non-null    object
 3   sex       714 non-null    object
 4   age       714 non-null    float64
 5   fare      714 non-null    float64
 6   sibsp     714 non-null    int64
 7   parch     714 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 44.8+ KB

In [8]:
df["Age_Category"] = df["age"].apply(
    lambda x:"Child's" if x<18 else "Adult"
)

In [9]:
df.to_csv("cleaned_data.csv",index=False)